In [ ]:
range(5)

range(0, 5)

In [ ]:
range(0,5)

range(0, 5)

In [ ]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [ ]:
range(10,40,20,30)

TypeError: range expected at most 3 arguments, got 4

In [ ]:
r=range(10,20,30)

In [ ]:
list(range(r))

TypeError: 'range' object cannot be interpreted as an integer

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


**NUMPY**

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [ ]:
type(my_list)

list

In [4]:
empty_arr=np.empty(5)
empty_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
arr=np.array(my_list)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(15.2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,10)   #first arg is always less than second arg

array([], dtype=int64)

In [ ]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [ ]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [ ]:
np.arange(10,10)

array([], dtype=int64)

In [ ]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(6,10,dtype=int)

TypeError: argument for zeros() given by name ('dtype') and position (position 1)

In [ ]:
np.zeros(-10,dtype=int)

ValueError: negative dimensions are not allowed

In [ ]:
np.zeros(10,dtype=string)

NameError: name 'string' is not defined

In [ ]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((20,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
n1=10
print(np.ones(n1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
np.twos(2)

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
random.rand(3,2)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(2,3)

array([[0.54979023, 0.12025657, 0.75724519],
       [0.14674503, 0.82685048, 0.05490229]])

In [ ]:
np.random.rand(3,2)

array([[0.67420118, 0.37227305],
       [0.41989506, 0.81913023],
       [0.12369466, 0.6044699 ]])

In [ ]:
np.random.randint(2,20)

5

In [ ]:
np.random.randfloat(2,5)

AttributeError: module 'numpy.random' has no attribute 'randfloat'

In [ ]:
np.random.randint(2,20,5)

array([18, 16,  7,  7, 14])

In [ ]:
np.random.randint(-30,10,5)

array([ -1,  -9, -15, -10, -29])

In [ ]:
import numpy as np

In [ ]:
np.random.randint(10,10,(10,10))

ValueError: low >= high

In [ ]:
np.arange(1,12).reshape(3,4)

ValueError: cannot reshape array of size 11 into shape (3,4)

In [ ]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.arange(1,25).reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
b=np.random.randint(10,20,(10,10))
b

array([[10, 14, 11, 19, 11, 17, 18, 17, 15, 19],
       [11, 12, 17, 15, 19, 19, 18, 10, 18, 13],
       [18, 18, 16, 18, 13, 11, 11, 15, 12, 17],
       [13, 17, 12, 15, 11, 16, 14, 10, 13, 12],
       [10, 10, 10, 19, 10, 13, 16, 10, 19, 15],
       [19, 16, 12, 19, 16, 12, 16, 16, 12, 16],
       [13, 12, 15, 10, 11, 18, 14, 13, 18, 14],
       [11, 15, 12, 11, 15, 13, 12, 19, 13, 10],
       [17, 15, 14, 17, 11, 11, 15, 11, 14, 16],
       [18, 11, 11, 11, 11, 13, 10, 12, 12, 18]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b

array([[10, 14, 11, 19, 11, 17, 18, 17, 15, 19],
       [11, 12, 17, 15, 19, 19, 18, 10, 18, 13],
       [18, 18, 16, 18, 13, 11, 11, 15, 12, 17],
       [13, 17, 12, 15, 11, 16, 14, 10, 13, 12],
       [10, 10, 10, 19, 10, 13, 16, 10, 19, 15],
       [19, 16, 12, 19, 16, 12, 16, 16, 12, 16],
       [13, 12, 15, 10, 11, 18, 14, 13, 18, 14],
       [11, 15, 12, 11, 15, 13, 12, 19, 13, 10],
       [17, 15, 14, 17, 11, 11, 15, 11, 14, 16],
       [18, 11, 11, 11, 11, 13, 10, 12, 12, 18]])

In [ ]:
b[:]

array([[10, 14, 11, 19, 11, 17, 18, 17, 15, 19],
       [11, 12, 17, 15, 19, 19, 18, 10, 18, 13],
       [18, 18, 16, 18, 13, 11, 11, 15, 12, 17],
       [13, 17, 12, 15, 11, 16, 14, 10, 13, 12],
       [10, 10, 10, 19, 10, 13, 16, 10, 19, 15],
       [19, 16, 12, 19, 16, 12, 16, 16, 12, 16],
       [13, 12, 15, 10, 11, 18, 14, 13, 18, 14],
       [11, 15, 12, 11, 15, 13, 12, 19, 13, 10],
       [17, 15, 14, 17, 11, 11, 15, 11, 14, 16],
       [18, 11, 11, 11, 11, 13, 10, 12, 12, 18]])

In [ ]:
b[1:3]

array([[11, 12, 17, 15, 19, 19, 18, 10, 18, 13],
       [18, 18, 16, 18, 13, 11, 11, 15, 12, 17]])

In [ ]:
b[1,2]

17

In [ ]:
b[1,-1]

13

In [ ]:
b

array([[10, 14, 11, 19, 11, 17, 18, 17, 15, 19],
       [11, 12, 17, 15, 19, 19, 18, 10, 18, 13],
       [18, 18, 16, 18, 13, 11, 11, 15, 12, 17],
       [13, 17, 12, 15, 11, 16, 14, 10, 13, 12],
       [10, 10, 10, 19, 10, 13, 16, 10, 19, 15],
       [19, 16, 12, 19, 16, 12, 16, 16, 12, 16],
       [13, 12, 15, 10, 11, 18, 14, 13, 18, 14],
       [11, 15, 12, 11, 15, 13, 12, 19, 13, 10],
       [17, 15, 14, 17, 11, 11, 15, 11, 14, 16],
       [18, 11, 11, 11, 11, 13, 10, 12, 12, 18]])

In [ ]:
b[0:-3]

array([[10, 14, 11, 19, 11, 17, 18, 17, 15, 19],
       [11, 12, 17, 15, 19, 19, 18, 10, 18, 13],
       [18, 18, 16, 18, 13, 11, 11, 15, 12, 17],
       [13, 17, 12, 15, 11, 16, 14, 10, 13, 12],
       [10, 10, 10, 19, 10, 13, 16, 10, 19, 15],
       [19, 16, 12, 19, 16, 12, 16, 16, 12, 16],
       [13, 12, 15, 10, 11, 18, 14, 13, 18, 14]])

In [ ]:
b[-5,-2]

12

In [ ]:
a=np.random.randint(10,20,10)
a

array([16, 18, 18, 13, 12, 12, 12, 13, 13, 18])

In [ ]:
arr=np.random.randint(10,20,(10,10))
arr

array([[17, 11, 18, 16, 18, 18, 15, 11, 19, 11],
       [17, 11, 10, 15, 14, 18, 12, 16, 10, 10],
       [10, 15, 15, 19, 13, 17, 17, 19, 11, 11],
       [16, 10, 15, 11, 14, 10, 13, 16, 16, 11],
       [19, 11, 14, 15, 16, 12, 17, 13, 12, 16],
       [17, 16, 19, 16, 15, 16, 14, 14, 12, 12],
       [16, 15, 17, 10, 11, 14, 14, 11, 15, 10],
       [16, 10, 15, 14, 11, 15, 10, 14, 15, 19],
       [16, 17, 15, 18, 16, 15, 13, 10, 12, 13],
       [19, 16, 10, 15, 19, 18, 14, 19, 10, 12]])

In [ ]:
arr[::-1]

array([[19, 16, 10, 15, 19, 18, 14, 19, 10, 12],
       [16, 17, 15, 18, 16, 15, 13, 10, 12, 13],
       [16, 10, 15, 14, 11, 15, 10, 14, 15, 19],
       [16, 15, 17, 10, 11, 14, 14, 11, 15, 10],
       [17, 16, 19, 16, 15, 16, 14, 14, 12, 12],
       [19, 11, 14, 15, 16, 12, 17, 13, 12, 16],
       [16, 10, 15, 11, 14, 10, 13, 16, 16, 11],
       [10, 15, 15, 19, 13, 17, 17, 19, 11, 11],
       [17, 11, 10, 15, 14, 18, 12, 16, 10, 10],
       [17, 11, 18, 16, 18, 18, 15, 11, 19, 11]])

In [ ]:
arr[::-2]

array([[19, 16, 10, 15, 19, 18, 14, 19, 10, 12],
       [16, 10, 15, 14, 11, 15, 10, 14, 15, 19],
       [17, 16, 19, 16, 15, 16, 14, 14, 12, 12],
       [16, 10, 15, 11, 14, 10, 13, 16, 16, 11],
       [17, 11, 10, 15, 14, 18, 12, 16, 10, 10]])

In [ ]:
arr[:-3]

array([[17, 11, 18, 16, 18, 18, 15, 11, 19, 11],
       [17, 11, 10, 15, 14, 18, 12, 16, 10, 10],
       [10, 15, 15, 19, 13, 17, 17, 19, 11, 11],
       [16, 10, 15, 11, 14, 10, 13, 16, 16, 11],
       [19, 11, 14, 15, 16, 12, 17, 13, 12, 16],
       [17, 16, 19, 16, 15, 16, 14, 14, 12, 12],
       [16, 15, 17, 10, 11, 14, 14, 11, 15, 10]])

In [ ]:
arr.max()

19

In [ ]:
arr.min()

10

In [ ]:
arr.mean()

14.31

In [ ]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
from numpy import *

In [ ]:
arr

array([[17, 11, 18, 16, 18, 18, 15, 11, 19, 11],
       [17, 11, 10, 15, 14, 18, 12, 16, 10, 10],
       [10, 15, 15, 19, 13, 17, 17, 19, 11, 11],
       [16, 10, 15, 11, 14, 10, 13, 16, 16, 11],
       [19, 11, 14, 15, 16, 12, 17, 13, 12, 16],
       [17, 16, 19, 16, 15, 16, 14, 14, 12, 12],
       [16, 15, 17, 10, 11, 14, 14, 11, 15, 10],
       [16, 10, 15, 14, 11, 15, 10, 14, 15, 19],
       [16, 17, 15, 18, 16, 15, 13, 10, 12, 13],
       [19, 16, 10, 15, 19, 18, 14, 19, 10, 12]])

In [ ]:
median(arr)

15.0

In [ ]:
arr=np.arange(10,10,20)

In [10]:
arr=np.random.rand(10)
arr

array([0.33625796, 0.35163035, 0.42822103, 0.93974711, 0.93440017,
       0.61636583, 0.94836569, 0.53736137, 0.47361792, 0.06679045])

In [11]:
np.sort(arr)

array([0.06679045, 0.33625796, 0.35163035, 0.42822103, 0.47361792,
       0.53736137, 0.61636583, 0.93440017, 0.93974711, 0.94836569])

In [12]:
arr1=np.random.randint(10,20,10)
arr1

array([15, 17, 13, 14, 11, 14, 10, 18, 15, 10])

In [15]:
np.array(arr)
np.array(arr1)
np.concatenate((arr,arr1))

array([ 0.33625796,  0.35163035,  0.42822103,  0.93974711,  0.93440017,
        0.61636583,  0.94836569,  0.53736137,  0.47361792,  0.06679045,
       15.        , 17.        , 13.        , 14.        , 11.        ,
       14.        , 10.        , 18.        , 15.        , 10.        ])

In [17]:
arr.ndim  #returns the dimensions of an array

1

In [18]:
arr.size  #returns the size of an array

10

In [19]:
arr.shape #returns the shape of the array

(10,)

In [20]:
arr.reshape(5,2)

array([[0.33625796, 0.35163035],
       [0.42822103, 0.93974711],
       [0.93440017, 0.61636583],
       [0.94836569, 0.53736137],
       [0.47361792, 0.06679045]])

In [22]:
np.reshape(arr1,(5,2),order='C')

array([[15, 17],
       [13, 14],
       [11, 14],
       [10, 18],
       [15, 10]])

In [23]:
np.reshape(arr1,(5,2),order='F')

array([[15, 14],
       [17, 10],
       [13, 18],
       [14, 15],
       [11, 10]])

In [24]:
np.reshape(arr1,(5,2),order='A')

array([[15, 17],
       [13, 14],
       [11, 14],
       [10, 18],
       [15, 10]])

In [27]:
arr2=arr1[np.newaxis,:] #creating a new axis
arr2.shape

(1, 10)

In [28]:
arr2=arr1[np.newaxis,:] #row vector axis
arr2.shape

(1, 10)

In [29]:
arr2=arr1[:,np.newaxis] #coloumn vector axis
arr2.shape

(10, 1)

In [30]:
arr1

array([15, 17, 13, 14, 11, 14, 10, 18, 15, 10])

In [35]:
print(arr1[arr1>5])

[15 17 13 14 11 14 10 18 15 10]


In [36]:
print(arr1[arr1<5])

[]


In [37]:
 divisible_by_2 = arr1[arr1%2==0]
 print(divisible_by_2)

[14 14 10 18 10]


In [38]:
12 in arr1

False

In [39]:
arr1 %2==0

array([False, False, False,  True, False,  True,  True,  True, False,
        True])

In [41]:
np.stack((arr1,arr1))

array([[15, 17, 13, 14, 11, 14, 10, 18, 15, 10],
       [15, 17, 13, 14, 11, 14, 10, 18, 15, 10]])

In [42]:
np.vstack((arr1,arr1))

array([[15, 17, 13, 14, 11, 14, 10, 18, 15, 10],
       [15, 17, 13, 14, 11, 14, 10, 18, 15, 10]])

In [43]:
np.hstack((arr1,arr1))

array([15, 17, 13, 14, 11, 14, 10, 18, 15, 10, 15, 17, 13, 14, 11, 14, 10,
       18, 15, 10])

In [45]:
 data = np.array([1, 2])
 ones = np.ones(2, dtype=int)
 data + ones


array([2, 3])

In [46]:
 data - ones

array([0, 1])

In [47]:
data * data

array([1, 4])

In [48]:
arr1.sum()

137

AttributeError: 'numpy.ndarray' object has no attribute 'mul'